### ISSUE TITLE
Items relabelled after reloading

### ISSUE THREAD

**Issue by rmvandijk** [rschurade/Ingnomia#1]
I couldn't see any issues here so I'm assuming it wasn't reported yet.

After loading a game, a lot of my items changed to different stuff.
I've added images of two of the funniest, a strawberry sausage omelette and a cotton skull from which where a strawberry and raw cotton before saving and loading:

![image](https://user-images.githubusercontent.com/43349299/45636133-281b9080-baa7-11e8-90e1-38352af22dc2.png)

![image](https://user-images.githubusercontent.com/43349299/45636056-ed195d00-baa6-11e8-8b42-5fe09925d4d8.png)

Let me know if this was already known or if you want to see the savegame.

Thanks for all the effort, I liked Gnomoria but always thought it could be more, which this will hopefully become.

**Comment by rmvandijk** [comment]
I've looked into it a bit (however the this kingdom might be lost due to the strange magic :P) and I found that most of the bugged items had their ID reduced by 2. Don't know if that helps

Regards, rmvandijk

**Comment by rschurade** [comment]
This happens to older saves when I add items or materials. So you probably lost you kingdom to early access save game breaking, sorry.

**Comment by rmvandijk** [comment]
Ok, that explains it then.
The kingdom just got started, so no big loss and part of the early acces experience :).

Besides, I had a good laugh at all the weird items
