### ISSUE TITLE
Removing old networking code

### ISSUE THREAD

**Issue by Ext3h** [rschurade/Ingnomia#106]
The code base is currently cluttered with remnants of an old, failed "multiplayer" experiment based on full state replication, which is not going to be ever completed in the originally planed form.

The classes `NetworkClient`, `NetworkServer`, `NetworkCommand` as well as `GameState::setAcceptChangeSets` `GameState::addChange`, `GameState::addChange2` and `GameState::getChangeSet` can be removed entirely, including whatever logic was surrounding them.

**Comment by Carlosgrr** [comment]
PR 108 is removing theses classes and some others related to networking.
https://github.com/rschurade/Ingnomia/pull/108
