### ISSUE TITLE
Crash at military tab.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#11]
At military tab one of the gnomes who are in squad, not present as icon, but appears in the list. After trying to add another gnome, game crashes.

Also when trying to select another squad, previous is being duplicated.
![image](https://user-images.githubusercontent.com/3108850/60768158-5ddb4580-a0ca-11e9-8fab-c305e46f3db9.png)
![image](https://user-images.githubusercontent.com/3108850/60768223-30db6280-a0cb-11e9-8efd-ee0f3e77f0ff.png)
Reloading not fixing this.

**Comment by rschurade** [comment]
Old qt gui, can be reproduced anymore.
