### ISSUE TITLE
Workzone color bug

### ISSUE THREAD

**Issue by CptVolkow** [rschurade/Ingnomia#117]
Workzone color mismatch or stuck on red.
[6.zip](https://github.com/rschurade/Ingnomia/files/5655566/6.zip)
![Screenshot 2020-12-08 000722](https://user-images.githubusercontent.com/75645347/101412171-ce534b00-38ea-11eb-83d1-42c9658fc8ac.png)

**Comment by Ext3h** [comment]
Ever seen this happening again since? There is some really weird *inconsistent* coloring in that screenshot (e.g. the yellow and red *mixed*  in the distillery), but from the save game it doesn't look like anything is actually bugged, just the workshops are unable to work for legit reasons.

**Comment by comaldave** [comment]
I have not seen this. I shall report it if I do see it.

**Comment by CptVolkow** [comment]
The bug has not repeated itself
