### ISSUE TITLE
Hauling problem.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#12]
I think it's rather complex, but i have this issues right now:
1. Gnomes tend to ignore wheelbarrow and sacks.
2. Gnomes try to reach unreachable place.
https://mega.nz/#!Q1QTkYCR!3lITkZi3Sig8DPYidZ05b5V3HETdbipBM606TijZ57g  (modified db are included just in case)

![image](https://user-images.githubusercontent.com/3108850/60873837-ac5e2080-a23f-11e9-952f-f5c69d9a4237.png)

**Comment by rschurade** [comment]
That's a bit strange. No item exists at 0 0 0

Also I can't really start debugging with modified db's. 

I also see that save has the disappearing bed bug. I can't really reproduce it and I can't see in the code where it could go wrong. So what are you doing there :)

**Comment by lokkiser** [comment]
To reproduce bed bug, i simply place a lot of containers. Some of them turn out to be beds, when i check upon them.

Ok, i'll try to reset db and see if that helps.

**Comment by rschurade** [comment]
I can do what I want but I don't get it. So if by chance you have a save game with the crate construction jobs already in place and the bug happening when the job gets done would help. That's a pretty severe thing and I want it gone.

**Comment by lokkiser** [comment]
Tried creating new world (minimal size 50, flat, otherwise default). Beds are counting properly and do not being placed instead of containers. I'll try to use the same world with my old (apparently damaged) DB and see if that still causes this bug.
p.s. when can we have 0.6.6.1?)

**Comment by rschurade** [comment]
on steam go to betas and activate indev

**Comment by rschurade** [comment]
closing this for now, there has been a lot of work on stockpiles and containers and this should be fixed now
