### ISSUE TITLE
Game renders shrinked in its window in hidpi

### ISSUE THREAD

**Issue by njoyard** [rschurade/Ingnomia#120]
Reproduced on Linux, using a build on master as of 32dd840f.

**Steps to reproduce:**
Start the game on Wayland with a HiDPI setup

**Expected:**
Game renders using the complete window surface

**Actual:**
Game renders using only the lower left corner of the window surface (scaled down from window dimensions by the display scaling factor in each dimension).
Mouse coordinates are scaled correctly, which means you have to aim where things would be if the game was rendered at full scale.
Switching to fullscreen, resizing the window, etc. does not alter behaviour.

The screenshot below shows the main menu but running an actual game exhibits the exact same behaviour. Game behaves completely normal apart from this.

![image](https://user-images.githubusercontent.com/127842/103221756-aa9c8700-4923-11eb-9553-ea74b44399ae.png)

**Workaround:**
Start the game with xwayland (using `QT_QPA_PLATFORM=xcb`).

I'm currently trying to understand and fix the issue but I'm a complete noob in Qt so it may take ages :slightly_smiling_face:

**Comment by Ext3h** [comment]
The fix for that probably isn't to be found in Qt, but rather via OpenGL API, setting the correct viewport which would correspond to the full window size.

So you will need to find out the size of the window in pixels (not the DPI scaled dimensions), and try to set that.

Unfortunately can't help you, as I don't have a similar setup available.

**Comment by njoyard** [comment]
Looks like taking scaling into account when calling `MainWindowRenderer::resize` fixes the issue. We can get the scaling from `QScreen::devicePixelRatio` provided we manage somehow to get which screen the app renders to.

**Comment by Ext3h** [comment]
Thank you, there was actually a little bit more which had to be done to make it work correctly.

Looks like on your system Qt was configured to run in DPI aware mode regardless of whether the application supported that yet. Should be fully DPI aware now.
