### ISSUE TITLE
Building job stuck due to floating items

### ISSUE THREAD

**Issue by PoweredByMave** [rschurade/Ingnomia#128]
ROOT CAUSE LISTED BELOW IN COMMENTS.

Floating item (soil, in this case) created by mining a ramp adjacent to a "build floor" order WHILE a gnome is in the process of placing the floor.

Possibly registering the pending floor's z level to be the proper height to drop the soil from the mined ramp.

Google drive link for the save recreating the issue.

[https://drive.google.com/drive/folders/1OtczuhWFYIsaw7npw78sRMDexKZkEfRO?usp=sharing](url)

_Idle gnomes (with construction profession at top of priorities as well as sole profession)
No other build orders
No mining orders
Sandstone raw stone & Dirt soil is available both in stockpile as well as out of stockpile.

Recreating:
1. built stairs next to wall
2. built stairs standalone
2. created build soil floor order on both sets of stairs.

Once this happens, I am also no longer able to build soil stairs.

Attempted fixes:
1. Pause game
2. Cancel build order
3. Unpause
4. wait a few seconds
5. recreate soil floor build order

Attempted with sandstone raw stone as well.
Attempted in Multiple directions
Mined fresh soil and stone

Result:
Unable to build overhanging soil/stone floors from top of stairs
Unable to build supported soil/stone floors from top of stairs
Able to build overhanging wood log floors from soil stairs.

What fixes* issue:
Saving/quitting and reloading game solves the issue for previously created build orders, then issue repeats.

Will test more options later. (Including new savegame)_

Mave

**Comment by comaldave** [comment]
I am having similar problems. The builder has everything to build Stone Mason Workplace and nothing else to do but he refuses to build it. I tried to save, exit, continue but he is very stubborn.

I would classify this as a Critical Error as there is no workaround and it prevents further progress.

**Comment by rschurade** [comment]
If it persists through save/reload then please open a new issue and attach the save game.

**Comment by Ext3h** [comment]
Actual cause:

> Recreated in new save multiple times. 
> 1. build single block width wall of soil. 
> 2. build ramps along the wall. 
> 3. Set miners to mine ramps away. 
> 4. Let game time go for a few ticks, such that the miners have almost finished mining the ramp.
> 5. Set build floor order along top of wall. 
 >Gnomes will green light the build floor order, and start building.
If the miners finish mining the ramp adjacent to a build order that is in the physical process of a gnome building, the soil from the dirt ramp that was mined will register right beside the build order, effectively floating and unreachable.

So floating item, when then bugs out any jobs related to that item.

Hard to track down because of #53, but distinct from #111.

**Comment by PoweredByMave** [comment]
Thank you for updating the post. 

> I am having similar problems. The builder has everything to build Stone Mason Workplace and nothing else to do but he refuses to build it. I tried to save, exit, continue but he is very stubborn.
> 
> I would classify this as a Critical Error as there is no workaround and it prevents further progress.

Look closely for floating build requirements. I have ran in to the issue by mining a ramp while a gnome is building a floor directly in front of the ramp. The ramp was mined while the gnome was placing the floor and the dirt was dropped on the same level of the floor being built. Effectively suspending the dirt in the air.

Mave

**Comment by PoweredByMave** [comment]
Verified game files, new save still reproduces issue on my end.

Savegame setup with mining and build orders. Upon resuming, the issue presents itself on my end.:

https://drive.google.com/drive/folders/1rfUDDPmPvWzkhJ0krvMFBpIUWyTsM49w?usp=sharing


Mave
