### ISSUE TITLE
Bug - Incorrect Dialogue on Workplace or Stockpile

### ISSUE THREAD

**Issue by comaldave** [rschurade/Ingnomia#129]
# Expected Behavior
When clicking on the Carpenter shop, I expect to see the dialogue for the Carpenter shop.
# How to duplicate the bug
* After clicking on the Crude Workshop and reviewing the dialogue,
* Click on the Carpenter Shop, the last previous dialogue will appear, not the dialogue for the Carpenter Shop.
# Work Around
* Click on some dirt to clear the dialogue.
* Click on the Carpenter Shop and now the correct dialogue box appears.
# Note
The foregoing is an example, the problem seems to be with all Workplace and Stockpiles.
Not a critical error but quite aggravating.

**Comment by rschurade** [comment]
I cannot reproduce the issue neither with workshops nor with stockpiles.

**Comment by comaldave** [comment]
I loaded the most recent updates this morning. I am unable to recreate the problem. Close #129.

**Comment by Ext3h** [comment]
Was probably real bug, and fixed by 95415044b1958ede1e15c804f92abff1622277af
