### ISSUE TITLE
Fell Trees chooses empty cells. [Indev]

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#13]
![image](https://user-images.githubusercontent.com/3108850/60908080-b7d33b00-a283-11e9-8952-6b510fdcbf1f.png)

**Comment by rschurade** [comment]
Can't reproduce. I can select the fell tree job and select a big area and it only selects trees and creates jobs for them. Have you selected some other job before or pressed any keys?

**Comment by lokkiser** [comment]
Remove plants, but i'm not sure.

**Comment by rschurade** [comment]
Ok I see something is not right when having another job selected and selecting the fell tree job

**Comment by rschurade** [comment]
fixed in 0.6.6.2
