### ISSUE TITLE
Drop down menu not showing

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#14]
When trying to create a new world, I can`t select difficulty levels or items with the drop down menu.

When I click the arrow with my mouse, the menu opens, but I can't see it. I know the drop down menu is opened because I can select other options there, but I can't see it in my screen.

Playing 0.6.6, with a Radeon RX 560, Windows 10.

![image](https://user-images.githubusercontent.com/50493006/61284592-2bf76c80-a7b7-11e9-919a-38a03c8f8fe6.png)

**Comment by rschurade** [comment]
Hard to do anything about it. It's standard framework stuff and since it works here can't really reproduce. So I can just leave this open for now and we'll see if that bug occurs anywhere else.

**Comment by Daxtgnomoria** [comment]
To help with futures issues, I did some further testing and found that the problem seems to be caused by activating the option "frameless window'" on Video Menu. If I disable "frameless window'" on Video Menu, the drop down menu works fine on the New Game option.

Also, drop down menu works fine in-game (after loading a save), even with "frameless window'" activated.

My problem seems to happen only on main menu (embark screen), and with frameless window activated.

**Comment by rschurade** [comment]
Ok that explains some things. The frameless window stuff in Qt is not without quirks. Switching to another frame work would be a few months work though.

**Comment by Ext3h** [comment]
QT UI is gone. If similar issues occur again, they are unrelated.
