### ISSUE TITLE
Placing grove skips plants

### ISSUE THREAD

**Issue by comaldave** [rschurade/Ingnomia#142]
### When placing a **grove**, I have holes in the **grove** due to the existence of wildflowers.

# Work around
After placing the **grove**  
Forage the wildflowers  
Remove any other plants  
remark the **grove** to include the holes.

# Enhancement desired
When marking the **grove**, include any unmarked plants as well, same as **farm** and **pasture**.  
I can then forage and remove plants at leisure.

**Comment by rschurade** [comment]
done
