### ISSUE TITLE
Missing tiles cause crash when clicked on

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#15]
I already reported it in-game, but needed to input more information.

In the in-game report, I mentioned that the game was created with missing tiles that crashed when clicked on (found 2 so far). However, after loading previous saves, I realized that the map was NOT created with this missing tiles. The  tiles went missing at some later unknown moment. I`ll try to load all previous saves to see when it was created.

![image](https://user-images.githubusercontent.com/50493006/61450873-fafe6f80-a94f-11e9-9b96-ad0818a43e61.png)

**Comment by rschurade** [comment]
Ok the crash is a missing null pointer check for the sprite. That's easy to fix. The question remains why is the floor disappearing.

**Comment by Daxtgnomoria** [comment]
I just loaded previous saves and the spot to the right had a carrot plant (that was foraged) and the spot to the left had wheat (harvested).

Removing the missing tile and building it again fixed it.

I tried harvesting harvesting both tiles in a previous save, but could not reproduce the bug.

**Comment by rschurade** [comment]
closing for now, but keep an eye out
