### ISSUE TITLE
Place your pending suggestions here before they get proper interest

### ISSUE THREAD

**Issue by Daynvheur** [rschurade/Ingnomia#162]
This thread is for the everyone's awesome pending suggestions that are not on the roadmap today but might be somewhat valuable, and share thoughts about 'em.

Please, share yours, and/or join the discussion.

**Comment by Daynvheur** [comment]
My personnals:
- Have a "paint" mode, similar to the "Cut trees" one, but targeting farm/grove/pasture type helping changing seeds en masse
- Have an "any" mode on farm/grove/pasture to let them accept any seed/seed(/acorn/pine)/animal available
- Name the personalised "Set up" preset(s)
- Add a slight border around zones, to visually distinguish them
- Add some Z-layer "pollution" when generating layers (-> have 1 or 2 sandstone visible on the surface even when the start flatness is 0%, that could help making the first workshops, and vary the undergrounds, and ease new player experience tempting them to look at undergrounds)
- Add a "follow gnome" camera option
- Inform what kind of trader has arrived ("An [animal] merchant", "A [military] merchant", ...)
- Show Gnomes/Animals states in a panel
- Show Gnomes/Animals/Resources history panel
- Engage more than 1 gnome for some heavy jobs, the more gnomes the faster
- Show oak acorns and pine cones in seed category, along with willow and birch seeds in the "Set up" and "Stockpiles" page
- Make the game less generous in seed quantities
- Implement a decay system
- Disallow selection of stockpile filter for containers not allowing such category (namely "seeds" on crates-only stockpile)
- Extend containers max value above 255
- Don't bother me with New Gnome arrivals, I want an option to automatically proceed with gnome arrivals:
-- Refuse all requests
-- Accept all requests
- Automatic "Remove plants/trees/blocks" job when placing a building on top of them
- Add more starting drinkable things (fruits and vegetables)
- Add leaves/trunk/root "blocks" to place (and consider them as decorative only)
- Revamp trees as the sum of more smaller entities (trunk, leaves, roots)
-- Vary tree heights and shapes
-- Join nearby leaves
-- Expanding tree branches
- Add a "move this pending job to another workbench" button
- Collect seeds from trees, without felling them
- Add buttons to manage the view, likely turn camera around, change zoom (+zoom reinit), change level.
- Improve job lookup to nearest path if possible (instead of by history)
- Add floor's physic
- Reduce the tree encumbrance to the only 4 direct neighbouring cells, in order to permit the trees to grow diagonally from each other

**Comment by Ext3h** [comment]
Please don't. Developers are getting an notification for every. Single. Update. On these tickets.
