### ISSUE TITLE
Item count on market stall not working correctly

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#18]
I noticed that item count on market stall is not correct, if you have more than one quality type of the same item. When you click to sell any amount of a item that has different quality, the counter resets to the total amount of that item (not only the selected quality). Screenshots to make easier to understand:

I have 297 orange wines on my stockpile (64 acceptable, 225 average and 8 good), but when I try to sell only one of the qualities, the number of that quality increases to the total amount of wines:

Before selecting one to sell, the numbers are correct:

![image](https://user-images.githubusercontent.com/50493006/61579658-07c1c580-ab00-11e9-9a86-4ac86d3235b2.png)

After trying to sell 1, the number of good wines raise from 8 to 296 (+1 to sell):

![image](https://user-images.githubusercontent.com/50493006/61579672-2aec7500-ab00-11e9-8662-752075cf397b.png)

I tested it, and it happens with any items that I have more than one quality available, and the value of the sale is accepted, even if those items do not exist.

**Comment by rschurade** [comment]
I see the problem in your last save game. Base looks good btw.

**Comment by Daxtgnomoria** [comment]
Well, for now it's just and amass of gnomes, food, drink and workshops, but I intend to improve their QoL with time! On a side note and totally unrelated question, is it possible to make metal pickaxes? I can't find them in workshops.

**Comment by rschurade** [comment]
It seems that recipe is missing, I'll add it next, after I found why the item count is borked.

**Comment by rschurade** [comment]
fixed is up

**Comment by Daxtgnomoria** [comment]
Seems to be working fine now! Can we close this issue for now?
