### ISSUE TITLE
Prices on market stall not calculating correctly

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#19]
When trying to sell items, several of them have a wrong price tag after selecting them to trade, i.e. the price in (xx) is different than the price in the total offer:

![image](https://user-images.githubusercontent.com/50493006/61579812-190bd180-ab02-11e9-9637-8672efb6b0f5.png)

This is only a small selection, but I noticed that it happens with a lot of items, regardless of its quality. In some cases, when selling multiple items of the same quality, the price per item varies.

**Important**, I've only seen this happen when I have more than one quality of the same item. In the case of buckets, after selling all buckets of other qualities and closing and opening the market stall again, the price of bad quality bucket was correct.

**Comment by rschurade** [comment]
that might be part of the item count issue

**Comment by rschurade** [comment]
can this be closed?

**Comment by Daxtgnomoria** [comment]
Haven't seen the problem again. I think it is safe to close.
