### ISSUE TITLE
Spritesheet?

### ISSUE THREAD

**Issue by ftzi** [rschurade/Ingnomia#191]
Hi, do this have a spritesheet to get the images from? I am tinkering on a side project and it would serve me well!

**Comment by ArhinZi** [comment]
> Hi, do this have a spritesheet to get the images from? I am tinkering on a side project and it would serve me well!

Hi, You can download it from here https://github.com/rschurade/IngnomiaBuildDeps/raw/master/tilesheet.zip

**Comment by ftzi** [comment]
Many many thanks! This is awesome! 😊
