### ISSUE TITLE
Checkbox css color

### ISSUE THREAD

**Issue by scottfriebel** [rschurade/Ingnomia#2]
I am unable to see the checks in checkboxes. I noticed that styling was added via an external css file and in that file there is a QCheckBox section but it doesn't have a color specified. There is also a QCheckBox[Type=EmbarkScreen] section with @ColorButtonText as the color. However it appears that @ColorButtonText is white (which makes sense since the buttons are medium to dark gray) but this means the checks are white and the checkboxes have a white background. I added color: black; to the main checkbox section and this fixes the issue.

**Comment by rschurade** [comment]
It's kind of a strange issue because it works on some machines, namely my dev machine with Win10, and doesn't on other like my laptop with Win10. I  fixed it in the indev branch already by applying checked and unchecked png to the css.  The text color shouldn't affect the checkbox check.

**Comment by scottfriebel** [comment]
Yea that is strange. I'm running Win10 as well where it isn't working. Changing the text color did affect the color of the checkmark for me so even if it isn't the "right" fix, at least I can see the checks until the new update :)

**Comment by pengliheng** [comment]
sure
