### ISSUE TITLE
Feature / change request for colodblind people

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#20]
Is it possible to change (or explain how to change) the colors from schedule color code?

As I have colorblindness - deuteranopia (mild one), I can't properly see the differences from sleep and training colors:

![image](https://user-images.githubusercontent.com/50493006/61580122-2034de80-ab06-11e9-8074-da428f6fc3e9.png)

Is it easy to change that?

Also, most people don't know, but close to 8% of male population have colorblindness, and of those, almost 65% have the type deteranopia. If I see any other colors that might confuse us, I will post here to see if something can be done about that.

Thanks!

**Comment by rschurade** [comment]
\steam\steamapps\common\Ingnomia\content\variables.def

That's even moddable though I'd have to check if the mod mechanism still works, but should.
