### ISSUE TITLE
Carpenter workshop stopped working

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#21]
I reported it in-game, but placing here to help track.

I tried deconstructing and rebuilding the workshop, but nothing happened.

I noticed something strange. After dismantling all of my carpenters, I noticed that if I try to build something from the workshop, after I build a new carpenter, it will start with a long list of items to build, that were ordered when it was deconstructed.

Also, even stranger, if I dismantle my carpenter and rebuild it in some other place, far from the initial place, it starts to work again. But if I rebuild it in the same spot, it stops working.

After deconstructing it, I noticed there there is a sprite located there, that I cant click.
![image](https://user-images.githubusercontent.com/50493006/61581605-875b8e80-ab18-11e9-8034-cfc8ff659fd1.png)

**Comment by rschurade** [comment]
I checked the save. The saved job with the carpenter has no required skill set so no gnome will pick it up. No clue how you managed that. Adding some clean up code to make it possible to reset the job queue.

**Comment by Daxtgnomoria** [comment]
Last thing I remember doing there was building lots of crates and 3 beds. After some time I noticed that the carpenters were not working there.

I will try to delete the chisel and the workshop located there by editing the save and will report if the bug happens again.

thanks

**Comment by Daxtgnomoria** [comment]
Found another stance of workshops that stop working. It is in the same save that I uploaded in the stockpile thread.

This time is my tailor workshop that stopped working. What I noticed is that in both times (carpenter and tailor), I had ordered a longer list of items to build in the map (boxes and sacks)

I did not use the crafting button, but a built something like 15 sacks on a stockpile, and this tailor was accepting generated jobs.

After deconstructing the tailor, a small spot where the resulting items were placed remained marked, as if it was a stockpile.

![image](https://user-images.githubusercontent.com/50493006/61594483-5cd70780-abe4-11e9-82eb-e7a9e2437b78.png)
(tailer was in the blue area, and red square is what was left after deconstructing it).

I can order the deconstruction of the red square, a gnome goes there, finishes the job, but nothing happens. I can order the deconstruction infinite times.

**Comment by rschurade** [comment]
It didn't craft those sacks because it had no string. Guess I need to work on the autocraft mechanic to allow recursive auto crafts and move them up.

The deconstruct issue is something different though.

**Comment by Daxtgnomoria** [comment]
You are correct. I didn't notice that, because so far the autocraft had been working fine, making every string I needed.

What is happening now is that every time I build and deconstruct a tailor shop, it leaves that spot behind and I can't construct anything else there.

There three spots there are after deconstructing 3 different tailors.

![image](https://user-images.githubusercontent.com/50493006/61594677-7711e500-abe6-11e9-8f7e-2c2e307a34cc.png)

Save for reference:

[save 79.zip](https://github.com/rschurade/Ingnomia/files/3414876/79.zip)

**Comment by rschurade** [comment]
Yes i saw that and found the issue. In the workshops_components table there is a double entry for that tile. That will be fixed next update but won't fix it for existing workshops.

**Comment by rschurade** [comment]
indev updated

**Comment by Daxtgnomoria** [comment]
> 
> 
> Yes i saw that and found the issue. In the workshops_components table there is a double entry for that tile. That will be fixed next update but won't fix it for existing workshops.

Just found the same problem with butcher and bonecarver workshop in the recent indev.

Deconstructing butcher and bonecarver leaver a spot on the floor that cannot be deconstructed anymore.
