### ISSUE TITLE
Crash after clicking thumbnail of dead goblin

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#22]
If you click a tile where an alive goblin is (open the screen with his thumbnail), then wait for him to die and click the thumbnail, the game crashes, because it cant find the info it is looking for.

![image](https://user-images.githubusercontent.com/50493006/61583684-3b6a1300-ab33-11e9-9063-0be1d5b25a0b.png)

**Comment by rschurade** [comment]
fixed in 0.6.6.8
