### ISSUE TITLE
Event "goblin raid" start again after loading

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#25]
Well, yet another bug to report.

I just noticed that if you save during a day that you had a goblin raid, even after killing all of them, another raid happens as soon as you load the game. 

I had 3 raids on the same day, all of them happening as soon as I loaded the game that was saved on the same day.

I think the same happens with traders, but haven't tested it yet.

In this save I just had a raid (dead goblins are by the door), and as soon as you un-pause another raid begins.
[85.zip](https://github.com/rschurade/Ingnomia/files/3415109/85.zip)

**Comment by rschurade** [comment]
Yes I know. The event manager status doesn't get saved right now

**Comment by Daxtgnomoria** [comment]
Also, if you save after a raid star starts, then save (before killing them) and loads the game, the previous goblins disappear and a new raid starts.

But if you save AFTER killing them, their bodies remain on the floor.

**Comment by rschurade** [comment]
fixed in 0.6.7.3 
added saving of monsters
refactored event manager and added saving/loading of state

**Comment by Daxtgnomoria** [comment]
Is it safe to use current save after you upload it, or should I create a new one?

**Comment by rschurade** [comment]
i have a crash with your save from the bread issue, so maybe new save is required

**Comment by rschurade** [comment]
also it's up already
