### ISSUE TITLE
Containers missing it's content types.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#3]
I'm quite sure that it's temporary, but it makes them not as useful as they should be.

**Comment by rschurade** [comment]
Can you elaborate?

**Comment by lokkiser** [comment]
![image](https://user-images.githubusercontent.com/3108850/60754592-ea630680-9feb-11e9-91d1-b814011f17f4.png)
Had to edit db to allow items to be stored in it.

**Comment by rschurade** [comment]
Will be fixed in 0.6.6.1 Moved container and category/grouping settings to the Items table so it easier to see if an entry is missing.

**Comment by rschurade** [comment]
I updated indev on steam. It will probably need a new game. I also switched bags and sacks. Sacks are now the buildable container on stockpiles and bags are carry containers.

**Comment by rschurade** [comment]
Closing this, container setting is now column in the item table. If a setting is missing or should be changed it can discussed in suggestions.
