### ISSUE TITLE
Build floor over multi-level tree

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#31]
I was able to build floor on top of a tree, essentially "cutting" it in half. 

Even on the tile where the trunk was supposed to be, I was able to build a floor. After ordering to cut such tree, her cut logs appeared on the top floor, whereas one single log (from her lower trunk I guess) appeared on the bottom floor.

![image](https://user-images.githubusercontent.com/50493006/61914251-d13cde00-af37-11e9-9416-01e1bf908174.png)

While further testing, I tried to build things around the second floor of the tree , on the same tile as her foliage and the middle trunk. I was able to build walls and scaffolds on the same tile as her foliage and was also able to place order to build scaffolds on her second level trunk. After a while the game crashed.

Since I ordered all things at the same time and used fast forward, I'm not sure which of it caused the crash.

**Comment by rschurade** [comment]
Why do you do that, leave the tree alone.

**Comment by rschurade** [comment]
fixed in 0.6.7.8

**Comment by Daxtgnomoria** [comment]
I was trying to build a treetop house! My gnomes are strange ones, they are afraid of cabin fever.
