### ISSUE TITLE
Crash when clicking stockpile that was deleted.

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#32]
I have a stockpile that was deleted, but part of it remains seen on the map (I think I was ordering the removal of it and a save game came into effect, not sure though).

The stockpile is not shown on stockpiles tab but I can find it in stockpiles json. The only stockpile that could store cotton seeds. After deleting it, the game crashes when I click on it.

![image](https://user-images.githubusercontent.com/50493006/61998921-d1131e80-b0ae-11e9-8e07-ad6abf880d81.png)

[29.zip](https://github.com/rschurade/Ingnomia/files/3438530/29.zip)

**Comment by rschurade** [comment]
Can you confirm this is still and issue or can we close it?

**Comment by Daxtgnomoria** [comment]
Didn't happen again. Closing for now.
