### ISSUE TITLE
Command Craft To is counting total items, not speciffic materials ordered

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#34]
Not sure if this is intended or not, but the order Craft To is not counting the specific material that I set to craft, but rather the total amount of the item type available.

For instance, I have two orders in the saw mill: 
-Craft to 100 pine planks
-Craft to 150 orangewood planks.

Both orders are already suspended, as if they had reached, but I have 62 orangewood planks 92 pine planks.

![image](https://user-images.githubusercontent.com/50493006/62000128-e47eb380-b0c7-11e9-976e-99f6c7c089ba.png)

**Comment by rschurade** [comment]
Yes there was still a TODO because it's a bit more complicated than it looks and lazy me pushed it back. Added it now and can be tested.

**Comment by Daxtgnomoria** [comment]
Just tested it and seems to be working fine now.

**Comment by Daxtgnomoria** [comment]
This is issue is back. I have a sawmill crafting to: 150 pine planks and 150 orange planks, it suspends both whenever the total reaches 150.

**Comment by rschurade** [comment]
Checked code and with a new game. It's working as intended. Need a save for proof.

**Comment by Daxtgnomoria** [comment]
I can't understand what happened! It is working now. For some reason both jobs were suspended and were not resuming itself. After loading and canceling the jobs, it got back to work. Will close and keep looking if it suspends again.
