### ISSUE TITLE
Stockpile remains on Stockpile Kingdom screen even after deleted

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#35]
I have an stockpile that remains on the stockpile screen even after deleted.

![image](https://user-images.githubusercontent.com/50493006/62001088-e9e7f800-b0df-11e9-9061-2ab2000833bd.png)

![image](https://user-images.githubusercontent.com/50493006/62001104-3a5f5580-b0e0-11e9-8bbb-4919db399c5e.png)

The stockpile is name "Carry" and I can see some jobs on json that are stuck there, even If all items are there and the stockpile is suspended. After deleting it in-game, the stockpile can be seen on the stocks screen.

In the save, all you have to do is delete the stockpile (near main entrance) an you can still see it there on kingdom screen.

[64.zip](https://github.com/rschurade/Ingnomia/files/3438768/64.zip)

**Comment by rschurade** [comment]
When a stockpile is deleted and there are still jobs out it will not get deleted immediately but first terminate those jobs and then delete the stockpile. So if you delete a stockpile while paused it will still be visible in the overviews. I get how this is confusing and remove it from there now when the field count is zero.

**Comment by rschurade** [comment]
fixed in 0.6.7.9
