### ISSUE TITLE
Bugged tree returned one level after  harvested for fruits only, foliage remained on map

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#36]
One of my trees returned one level after being  harvested for fruits.

Her lower trunk went back to second level (after sapling), but the foliage remained there, as a grown tree. Even after cutting the tree, its foliage remained there. Tile 74 87 100

![image](https://user-images.githubusercontent.com/50493006/62001272-b52a6f80-b0e4-11e9-9785-3079fe06724a.png)

[73.zip](https://github.com/rschurade/Ingnomia/files/3438789/73.zip)

**Comment by rschurade** [comment]
Can't really see from the save why it happened. Also a pretty rare one so lets just watch it for now to see if it happens again.

**Comment by Daxtgnomoria** [comment]
Haven't happened again. Lets close it for now and see if it is reported by anyone else?
