### ISSUE TITLE
Gnome stuck on tile after massive hunger

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#37]
So, I was testing how a colony would behave in case of massive hunger. First, some gnomes started to behave strangely, lagging a lot every time I clicked on their thumbnails, mostly when clicking their Log tab. They have hundreds and hundreds of "I'm hungry, looking for food, didnt find food". It is as if almost every tick they looked the map for food and lagged. The log got laggy to click after that.

After a while, one of my gnomes got stuck on the spot of a workshop and just remained there until dying, not moving at all. I  loaded a previous save and tested around this gnome a little more. 

After spawning food on the floor he was, he ate the food until 100 hunger, and only then he moved to another spot.

The problem is that now this gnome is breaking Newtonian physics and is at two places in the same time. On the tile that it was stuck I can still find his thumbnail and his sprite and also where he is moving around.

![image](https://user-images.githubusercontent.com/50493006/62001425-20297580-b0e8-11e9-8330-9b302f63a21a.png)
![image](https://user-images.githubusercontent.com/50493006/62001422-0ee06900-b0e8-11e9-8762-32ac9f8a7a0a.png)

[76.zip](https://github.com/rschurade/Ingnomia/files/3438801/76.zip)

**Comment by Daxtgnomoria** [comment]
Well, after saving, exiting  and  loading it again, his thumbnail and sprite disappeared from the place where he was stuck.

**Comment by rschurade** [comment]
That makes it hard to for me to see the bug then :) Anyway I'll see what I can do to reduce the checks and log messages.

**Comment by Daxtgnomoria** [comment]
Have you changed anything about checks and log message? Tell me when you do it and I'll stress test massive hunger in a colony again to see if we can close this.

**Comment by rschurade** [comment]
Yes I changed a bit, not sure if it fixes it entirely but should it improve the situation.
