### ISSUE TITLE
Door remaind on the tile info after getting deconstructed.

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#38]
I deconstructed a door and it remained there, as if it was still built. The item got removed and went back to stockpile, but tile info still shows a door, with no sprite.

![image](https://user-images.githubusercontent.com/50493006/62014612-36dcd480-b19b-11e9-94b7-7d167a83e8f3.png)

[106.zip](https://github.com/rschurade/Ingnomia/files/3439682/106.zip)

**Comment by rschurade** [comment]
Just checked, building and deconstructing a door on a new game works as expected. So what did you do? The save doesn't really help as the thing already happened.

**Comment by Daxtgnomoria** [comment]
I did nothing wrong! I swear! I just ordered some doors to be built and when I tried to deconstruct them, this was happening. I noticed that all my doors are behaving like that! Sometimes if I load a game and try this, it still happens

I'll test it a little more on a new game to see if I can reproduce it.
