### ISSUE TITLE
Crash while creating a new game (after embark screen)

### ISSUE THREAD

**Issue by Daxtgnomoria** [rschurade/Ingnomia#39]
Crash dump file (file was above github limit):

https://www89.zippyshare.com/v/Cg992utR/file.html

Here is the report created:

[Gnomes__PID__11760__Date__08_05_2019__Time_09_15_53PM__990__Second_Chance_Exception_C0000005_MultipleRules.zip](https://github.com/rschurade/Ingnomia/files/3469353/Gnomes__PID__11760__Date__08_05_2019__Time_09_15_53PM__990__Second_Chance_Exception_C0000005_MultipleRules.zip)

**Comment by rschurade** [comment]
first link is 403 forbidden

**Comment by rschurade** [comment]
Can't reproduce.
