### ISSUE TITLE
Attempt to move to unreacheble place for craft resource (64 64 128)

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#42]
Day  3, 12:34: JobType CraftAtWorkshop
Day  3, 12:34: Got  a new Carpentry job
Day  3, 12:34: Item is at 64 64 128 and must go to 59 54 99
Day  3, 12:34: JobType CraftAtWorkshop
Day  3, 12:34: Got  a new Carpentry job
Day  3, 12:34: Item is at 64 64 128 and must go to 59 54 99
Day  3, 12:34: JobType CraftAtWorkshop
Day  3, 12:34: Got  a new Carpentry job
Day  3, 12:34: Item is at 64 64 128 and must go to 59 54 99
Day  3, 12:34: JobType CraftAtWorkshop
Day  3, 12:34: Got  a new Carpentry job
Day  3, 12:34: Item is at 64 64 128 and must go to 59 54 99
I'm hungry.
Day  3, 13:07: Picked up an item.

**Comment by rschurade** [comment]
Can't do anything about it without a save

**Comment by lokkiser** [comment]
Day  1, 17:08: Got  a new Carpentry job
Day  1, 17:08: JobType CraftAtWorkshop
Day  1, 17:08: Got  a new Carpentry job
Day  1, 17:08: JobType CraftAtWorkshop
Day  1, 17:08: Got  a new Carpentry job
Day  1, 17:08: JobType CraftAtWorkshop
Day  1, 17:08: Got  a new Carpentry job
Day  1, 17:08: JobType CraftAtWorkshop
Day  1, 17:08: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:09: JobType CraftAtWorkshop
Day  1, 17:09: Got  a new Carpentry job
Day  1, 17:10: JobType CraftAtWorkshop
Day  1, 17:10: Got  a new Carpentry job

https://mega.nz/#!8w4GyQwB!f49lu9G1CWX9Bs3BO2rGDXH-X3NyPEfuxx1Jpna1PP4

**Comment by rschurade** [comment]
That's from temporary items not destroyed on startup, that was fixed already. You must have created the game before the fix went live.
