### ISSUE TITLE
Unknown job

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#43]
Day  6, 03:31: Got  a new Error: $SkillName_ job
Day  6, 03:31: Item is at 76 102 100 and must go to 72 99 100
Day  6, 03:48: Picked up an item.
Day  6, 03:50: Got  a new Error: $SkillName_ job
Day  6, 03:50: Item is at 76 102 100 and must go to 72 99 100
Day  6, 03:50: Picked up an item.
Day  6, 04:02: Picked up an item.
Day  6, 04:02: JobType PlantTree
Day  6, 04:02: Got  a new Error: $SkillName_ job
Day  6, 04:02: Item is at 77 102 100 and must go to 78 99 100

26.7z https://mega.nz/#!I5g0VSbL!K9ovAk856YiOpDdUo9xrT6qyoSndLHoV8DU_cipev6A

**Comment by rschurade** [comment]
The skill name was easy to fix. But I see the gnome just standing there, getting the job and aborting it over and over again. SO need to investigate what's going on here.

P.S.: that save is a mess (but good to stress test things)

**Comment by rschurade** [comment]
OK found the issue. There are a number of apple trees with missing trunk. Like on 69 99 100. Have any idea how that happened?

**Comment by lokkiser** [comment]
Can't say for sure, a lot of crashes and bugs like #40 with clipping/foraging, using selection.

**Comment by rschurade** [comment]
Crashes is not good, I don't really experience any with my limited testing so if you have any reproducible I would be very thankful.

**Comment by lokkiser** [comment]
Does ingnomia save anything upon crash, that i could forward to you?

**Comment by lokkiser** [comment]
> 
> 
> OK found the issue. There are a number of apple trees with missing trunk. Like on 69 99 100. Have any idea how that happened?

I'm having issues about building anything above x x 100. Could that be it?

**Comment by rschurade** [comment]
What kind of issues, just tested with your save it builds above level 100 just fine.

**Comment by lokkiser** [comment]
![image](https://user-images.githubusercontent.com/3108850/62820970-24887080-bb75-11e9-805c-703acd74e77e.png)
![image](https://user-images.githubusercontent.com/3108850/62820974-31a55f80-bb75-11e9-9c33-96f5ba5b6d46.png)

**Comment by rschurade** [comment]
The cursor doesn't hit anything on that level so it selects the tile below. Hold shift to keep the cursor on the selected level.

**Comment by lokkiser** [comment]
While building soil wall (without floor), some time after noticed this (errored block): 
![image](https://user-images.githubusercontent.com/3108850/62821010-04a57c80-bb76-11e9-985e-0033338020d1.png)
