### ISSUE TITLE
Population window Skills tab datagrid

### ISSUE THREAD

**Issue by AOmelaienko** [rschurade/Ingnomia#45]
A couple of UI improvement suggestions for this datagrid:
- it could really benefit from having a 'Profession' column with a dropdown list (IIRC, something like this was done in Gnomoria UI);
- on/off states of the toggle buttons look almost indistinguishable, at least for me. I would suggest making them larger (scale with font size setting perhaps?), and also changing the buttons' backgrounds for the state change rather than making a thin, almost invisible border to appear and disappear.

**Comment by rschurade** [comment]
That was on the todo list for a while already. Finally did it today.

Also made the checked mode of the skill buttons a bit more clearer.

**Comment by AOmelaienko** [comment]
Checked it out. Thank you for your hard work, looks really promising. A couple more notes:

- On dropdown lists:
    - as seen on the first screenshot attached, "Farmer" profession is displayed for all gnomes, however, only one gnome has appropriate skills selected (this is also true for individual gnomes' windows, please see second attached screenshot to make sure);
    - unless the datagrid is always (re-)sorted by profession column, a header with sort-on-click would be great.
- Skill toggle button UX still not great on my eyes, and my guess would be that I'm not the only one with such a problem. White border could improve things, I guess, since it'd be more in contrast with the background than black one. Maybe some other contrast colour.

![2019-08-19-0001](https://user-images.githubusercontent.com/8547283/63231410-092bfe00-c224-11e9-82f2-9ce878b39025.png)
![2019-08-19-0002](https://user-images.githubusercontent.com/8547283/63231523-80ae5d00-c225-11e9-937b-cbf219b54932.png)

**Comment by rschurade** [comment]
> unless the datagrid is always (re-)sorted by profession column, a header with sort-on-click would be great.

Not sure what you mean by that. You can sort the table by clicking on a skill label.

**Comment by AOmelaienko** [comment]
> > unless the datagrid is always (re-)sorted by profession column, a header with sort-on-click would be great.

> Not sure what you mean by that. You can sort the table by clicking on a skill label.

**Comment by rschurade** [comment]
You probably confuse something here. Gnomoria didn't have such a datagrid but at least I understand now.

**Comment by rschurade** [comment]
<img width="1478" alt="Capture" src="https://user-images.githubusercontent.com/780916/63256662-4fab4800-c278-11e9-8a20-f5aaae8a2227.PNG">

I must say I don't like the white border. But it's all in the css file and you can experiment with it yourself. I will also be possible to make mods for that file. It's located in \steam\steamapps\common\Ingnomia\content  This settings for these grid buttons start at line 470

**Comment by AOmelaienko** [comment]
> You probably confuse something here. Gnomoria didn't have such a datagrid but at least I understand now.

Well, it kind of had one, just no individual skill columns:
![2019-08-19-0003](https://user-images.githubusercontent.com/8547283/63264837-c22a2100-c294-11e9-8bda-abcb7776304a.png)

> I must say I don't like the white border.
Aesthetically I don't either, but at least it's visible very clearly now.

> But it's all in the css file and you can experiment with it yourself.
Will do just that, thanks a lot!

**Comment by rschurade** [comment]
Ah I didn't remember that window. Just checked it out. There is no way to sort, it just sorts when you close and open the window again.

**Comment by AOmelaienko** [comment]
> There is no way to sort, it just sorts when you close and open the window again.

Precisely. I think it'd be best if this behaviour was reproduced in Ingnomia, but if for some reason it couldn't be, a sortable Profession column header would do nice as well.

**Comment by AOmelaienko** [comment]
I also reiterate that currently profession column doesn't work as intended. Profession DDLs in individual gnomes' windows are broken as well.

![2019-08-19-0004](https://user-images.githubusercontent.com/8547283/63291254-d9d0cc00-c2cb-11e9-9d20-bb411f904101.png)
As seen here, all gnomes have 'Farmer' profession shown, but their active skillsets don't correspond to this profession.
![2019-08-19-0005](https://user-images.githubusercontent.com/8547283/63291378-0e448800-c2cc-11e9-99fe-9b4c77cd10f1.png)
Same is true for DDL in individual gnome's window, as could be seen here. If another profession is selected, and then 'Farmer' is selected again, proper skillset becomes activated:
![2019-08-19-0006](https://user-images.githubusercontent.com/8547283/63291487-4c41ac00-c2cc-11e9-9dac-f7e1bf31cb81.png)

**Comment by rschurade** [comment]
It's probably you never actually selected that profession so they still have all skills activated. Also if they don't have a profession selected they should default to the Gnomad profession which you probably deleted.

**Comment by rschurade** [comment]
Also you can have a profession selected and then still activate additional skills that don't belong to that profession.
