### ISSUE TITLE
Frameless window

### ISSUE THREAD

**Issue by AOmelaienko** [rschurade/Ingnomia#47]
Partial overlap with #14 – when game is started with **Frameless window** option is enabled in **Settings**&#x2011;>**Video**:
- dropdown lists in **New Game** menu won't show when corresponding dropdown button is pressed;
- internal windows (like **Population** window) won't show when corresponding button is pressed (note: they won't be shown neither in game's main window nor in aero peek, but will be visible in larger aero peek);
- when in-game menu opened through pressing **Esc** on keyboard, buttons will be available for clicking only after alt-tabbing;
- turning off **Frameless window** in-game does nothing, have to restart to restore proper functioning;
- proper behaviour of aforementioned features sometimes gets restored when user:
    1. Turns off **Frameless window**.
    2. Starts a new game or loads a game.
    4. Calls in-game menu with **Esc**.
    5. Alt-tabs.
    6. Quits to main menu.

All of the aforementioned works correctly when game is launched with **Frameless window** being turned off.

All of the above is tested with Win10x64.

**Comment by AOmelaienko** [comment]
Not 100% sure, but looks like window order somehow gets messed up.

**Comment by rschurade** [comment]
Yes the frameless implementation in Qt seems not to work 100% correct. I'm aware of that but can't do much other than replacing the complete window frame work.

**Comment by AOmelaienko** [comment]
Well, maybe get rid of it altogether, if you're sure that there's no way to resolve internal window ordering problems? Not of Qt, I mean, but of frameless window. There should be at least some other way to provide fullscreen-ish capabilities.

**Comment by rschurade** [comment]
This is fixed in the ui rewrite branch.

**Comment by AOmelaienko** [comment]
Can't find an option to check it in ui-rewrite.

**Comment by rschurade** [comment]
key F

**Comment by AOmelaienko** [comment]
**IT WORKS!!!**
