### ISSUE TITLE
Formation stays the same for all military squads.

### ISSUE THREAD

**Issue by Azmodania** [rschurade/Ingnomia#49]
5 minutes in the game I made a new uniform in the military menu, called 'none' with nothing equipped. Then I made a new position 'wotg' and selected 'way of the gnome', uniform 'none' and checked both boxes.
Then I made 2 formations 'soldiers' and 'workers', selected 'wotg' as position for all and checked 'avoid enemies' for both formations.  Then I made 2 squards 'First' and 'Second', selected formation 'soldiers' for the first squad and 'workers' for the second one. 
I used the first dropdown arrow to switch between the squads and noticed that they had the same formation. I set them again and whichever I set last was applied to both squads.

I went back to the positions tab and noticed a different phenomenon with the chosed perk. The perk would revert back to the default. When switching between positions the perk would not update.

**Comment by rschurade** [comment]
Currently rewriting that whole part. So this will be fixed next update. Closing this issue because it refers to code no longer present.
