### ISSUE TITLE
Jobs are not generated if workshop is built after item is required

### ISSUE THREAD

**Issue by Ext3h** [rschurade/Ingnomia#60]
When designating a newly built workshop to accept auto-generated jobs, it should retroactively also accept jobs which have been "lost" before.

E.g. when placing a "sack", but there is none in storage and there is no workshop which could produce it yet, then the job should still be generated when constructing a tailor with an "accept auto-generated jobs" at a later point in time.

Otherwise this results in the required items never being constructed, despite all prerequisites being fulfilled.

**Comment by rschurade** [comment]
fixed in 37c87cd4ba5c9db55ae38ead992c496adf99c78c
