### ISSUE TITLE
Statues and crafts in general are missing it's category in storage place.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#7]
Bone statues can not be categorized to be stored.

**Comment by rschurade** [comment]
Yes I'll probably move possible containers to the item table so I won't miss designations.

**Comment by rschurade** [comment]
statues should go to furniture->misc

**Comment by lokkiser** [comment]
Ok, thank you again. There should be a feature like search to determine where desired item should be stored.
