### ISSUE TITLE
Unclosable "gnomes arrived" dialogue

### ISSUE THREAD

**Issue by Ext3h** [rschurade/Ingnomia#84]
When not confirming the dialogue about arrived gnomes, but instead resuming the (automatically) paused game, then the dialogue remains open indefinitely with non-functional buttons.

Looks like not only an mistake in state handling, but also some possible side effects from #76

**Comment by rschurade** [comment]
fixed in 1a752bbc8efa62472ac0adc034ceb7b8d840cced
