### ISSUE TITLE
GUI is shrinking while playing the game. Also no Settings

### ISSUE THREAD

**Issue by mardeathappears** [rschurade/Ingnomia#85]
After playing nearly 4 hours the GUI has shrunk so much it is difficult to read. Also a restart of the game or a restart of the PC is not turning it back to the original size.

Also in the settings everything is empty and only one of the windows is showing something like "not implemented yet".
(Dont know if none of the settings are implemented yet)

Sorry if somebody opend an issue like that already.

![Guisize](https://user-images.githubusercontent.com/71144078/92950384-d7a05900-f45c-11ea-9e46-eb5d885476c4.PNG)
![Settings 1](https://user-images.githubusercontent.com/71144078/92950391-d8d18600-f45c-11ea-82d0-94b6207d9062.PNG)
![Settings 2](https://user-images.githubusercontent.com/71144078/92950393-d8d18600-f45c-11ea-87a2-8987e581d2d5.PNG)
![Settings 3](https://user-images.githubusercontent.com/71144078/92950394-d8d18600-f45c-11ea-859a-38ce25793f40.PNG)
![Settings 4](https://user-images.githubusercontent.com/71144078/92950396-d96a1c80-f45c-11ea-887d-7dcbf90bac56.PNG)

**Comment by rschurade** [comment]
Keys U and Z scale the gui. It's a known issue that this also happens when typing something in edit fields.

The settings dialogs aren't implemented yet.

**Comment by mardeathappears** [comment]
Thanks for the fast response
