### ISSUE TITLE
Errors in ingnomia.db.sql

### ISSUE THREAD

**Issue by ATeucke** [rschurade/Ingnomia#86]
There is a number of sprites and basesprites referenced that don't exists :
"WoodShortWallFrame" "WoodVShortWallFrame" "WoodPanelledShortWallFrame"  "TopLeftBorder"  "TopRightBorder"  "TopLeftWallBorder" "TopRightWallBorder"  "LeftBorder" "RightBorder" "LeftWallBorder"  "RightWallBorder"  "BottomLeftBorder"  "BottomRightBorder", ClothRollTableTopFR, ClothRollTableTopBL, AutomatonHead, ZygSeniorRedFR ClayURampFL ClayURampBR 
ClayURampTopFL ClayURampTopBR StoneURampFL OrangeMushroom_0 ... 8 StoneURampBR StoneURampTopFL StoneURampTopBR  MushroomGrassURamp_3_BL MushroomGrassURampTop_3_BL  PumpTop4 PipeExitWest

By my understanding, the following changes to ingnomia.db.sql should fix some of  them:

ClothRollTableTopFR
ClothRollTableTopBL
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClothRollTableTop','ClothRollTableTop',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClothRollTableTop','ClothRollTableTop','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClothRollTableTop','ClothRollTableTop',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClothRollTableTop','ClothRollTableTop','FlipHorizontal','BR',NULL);

AutomatonHead
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('AutomatonHead',0,'AutomatonHeadFR',0,'0 0',0,'Material',NULL,0);

ZygSeniorRedFR 
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('ZygSeniorRedFR','0 448 32 32','mushroom_biome_zygs.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('ZygSeniorRedBL','0 480 32 32','mushroom_biome_zygs.png');
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ZygSeniorRed','ZygSeniorRedFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ZygSeniorRed','ZygSeniorRedFR','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ZygSeniorRed','ZygSeniorRedBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ZygSeniorRed','ZygSeniorRedBL','FlipHorizontal','BR',NULL);

ClayURampFL 
ClayURampBR 
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURamp','ClayURampFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURamp','ClayURampFR','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURamp','ClayURampBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURamp','ClayURampBL','FlipHorizontal','BR',NULL);

ClayURampTopFL
ClayURampTopBR
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURampTop','ClayURampTopFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURampTop','ClayURampTopFR','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURampTop','ClayURampTopBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayURampTop','ClayURampTopBL','FlipHorizontal','BR',NULL);

StoneURampFL
StoneURampBR
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURamp','StoneURampFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURamp','StoneURampFR','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURamp','StoneURampBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURamp','StoneURampBL','FlipHorizontal','BR',NULL);

StoneURampTopFL
StoneURampTopBR
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURampTop','StoneURampTopFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURampTop','StoneURampTopFR','FlipHorizontal','FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURampTop','StoneURampTopBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('StoneURampTop','StoneURampTopBL','FlipHorizontal','BR',NULL);

OrangeMushroom_i islabeled as OrangeMushroom_Snow_1
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_0','0 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_1','32 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_2','64 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_3','96 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_4','128 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_5','160 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_6','192 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_7','224 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_8','256 224 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_0','0 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_1','32 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_2','64 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_3','96 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_4','128 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_5','160 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_6','192 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_7','224 320 32 20','seasonaldetails.png');
INSERT INTO "BaseSprites" ("ID","SourceRectangle","Tilesheet") VALUES ('OrangeMushroom_Snow_8','256 320 32 20','seasonaldetails.png');

MushroomGrassURamp_3_BL 
MushroomGrassURampTop_3_BL 
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURamp','MushroomGrassURamp_3_FL',NULL,'FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURamp','MushroomGrassURamp_3_FR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURamp','MushroomGrassURamp_3_FR',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURamp','MushroomGrassURamp_3_FL',NULL,'BR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURampTop','MushroomGrassURampTop_3_FL',NULL,'FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURampTop','MushroomGrassURampTop_3_FR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURampTop','MushroomGrassURampTop_3_FR',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('MushroomGrassURampTop','MushroomGrassURampTop_3_FL',NULL,'BR',NULL);

PumpTop4
INSERT INTO "Sprites_Frames" ("ID","BaseSprite") VALUES ('PumpTop','PumpTop1');
PipeExitWest
INSERT INTO "Sprites_Combine" ("ID","BaseSprite","Offset","Sprite","Tint") VALUES ('PipeExitNW','PipeWest','','','');

**Comment by rschurade** [comment]
fixed in https://github.com/rschurade/Ingnomia/commit/b3ec14aff097166605119738de04dde627f911c7

let me know if there's more

**Comment by ATeucke** [comment]
It looks like ClayRampTop is also missing.
Adding this should fix it.

INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayRampTop','ClayRampTopFR',NULL,'FR',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayRampTop','ClayRampTopFL',NULL,'FL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayRampTop','ClayRampTopBL',NULL,'BL',NULL);
INSERT INTO "Sprites_Rotations" ("ID","BaseSprite","Effect","Rotation","Sprite") VALUES ('ClayRampTop','ClayRampTopBR',NULL,'BR',NULL);

**Comment by ATeucke** [comment]
another anomality. The following Sprites had an extra ',' in their offset

		
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('Fruit',0,NULL,0,'0 12',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('Berries',0,NULL,0,'0 12',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('Leaves',0,NULL,0,'0 12',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('Mushroom',0,NULL,0,'0 12',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('Plant',0,NULL,0,'0 8',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('PlantWithFruit',0,NULL,0,'0 8',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('PlantGrowHelper1',0,NULL,0,'0 0',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('PlantGrowHelper2',0,NULL,0,'0 0',0,NULL,NULL,0);
INSERT INTO "Sprites" ("ID","Anim","BaseSprite","HasRandom","Offset","Rot90","Tint","DefaultMaterial","HasTransp") VALUES ('PlantGrowHelper3',0,NULL,0,'0 0',0,NULL,NULL,0);
