### ISSUE TITLE
Items change its material / workshops change their task.

### ISSUE THREAD

**Issue by lokkiser** [rschurade/Ingnomia#9]
I had a stonecutter set to autocraft up to 40 blocks, but after reload task is missing and instead my stonecarver that is neaby got a task to craft 40 cutting wheels, which were 1 or 2.
I also had a bolt of cloth made of Oak, which is impossible.

**Comment by rschurade** [comment]
Can you upload the save before that happens?

**Comment by lokkiser** [comment]
Ok, look around 132.115.102 and Tailor shop.
https://mega.nz/#!58Bm0ADA!MdfvKgTI9bE9ohS_kIOheInvVwAC-8J4fHYLycJdzu8

**Comment by rschurade** [comment]
Hmm, the string is already as oak string in the save game so I can say it's loading correctly, of course it should save them as oak :)

**Comment by lokkiser** [comment]
> 
> 
> Hmm, the string is already as oak string in the save game so I can say it's loading correctly, of course it should save them as oak :)

There's more, it crafts bolts of oak cloth. Compare two saves, it's somewhere there near 132.115.102.

**Comment by lokkiser** [comment]
Another thing, that may be related, may be not: beds being installed instead of barrels, this may be the answer, why beds aren't being considered as a part of dormitory.

**Comment by lokkiser** [comment]
Using 0.6.6.1 bug is still there.

**Comment by rschurade** [comment]
New game or old game loaded?

**Comment by lokkiser** [comment]
New one

**Comment by rschurade** [comment]
That's a tough one, I can't really see how that's possible and I haven't seen it yet. I would really appreciate it when you happen to have a save game before it happens and can reliably reproduce it.
