### ISSUE TITLE
Build dependency

### ISSUE THREAD

**Issue by Carlosgrr** [rschurade/Ingnomia#94]
To install the Qt 5.14 version, the official installer takes some 38Gb, but that should be trimmed to only the used components. Be that a readme instruction with a list or a custom installer downloaded directly from the Ignomiadeps repo.

Also the same can be said about Visual Studio Community, can't this be run on Visual Studio Code or even better, since the latest released version of Ingnomia removed the MSVC requirement, can't it be run on GCC, be it via MinGW or Linux?

All of that should be stated on the dependency section, as it is, there is a hefty dev requirement. Or even better, the Dependency list and installation instructions of said dependencies can be mantained in that other dependency repo, and stripped from this one.

(Since the current Ingnomiadeps doesn't accept issues, I am posting this here.)

**Comment by rschurade** [comment]
Qt only downloads 38Gb if you select like everything in the installer. The installed size is about 1.7Gb on my system. Same goes with visual studio. You don't need to make a full install with everything like the android or unity part.

Also this uses cmake now so you are free to specify any compiler that works and yes people are compiling it on Linux too.

**Comment by Carlosgrr** [comment]
Yes, but in the dependency list it is not specified which components are needed, so the problem remains...

**Comment by Ext3h** [comment]
Visual Studio Community Edition is already optional, by itself. If you prefer, you can of course just step down to using the command line tools only: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160

You can then pair these with Visual Studio Code or whatever you want to use as an IDE.

You can't use MinGW, as Noesis has pre-built components which won't be ABI-compatible in their C++ interface.
Clang might be compatible, but you really need to know what you are doing if you intend to mix it. Not going to document that here in detail.

As for Qt, what you "need" is the prebuilt binaries, only in the configuration you intend to use. E.g. "MSVC 2017 64bit". Or whatever compiler tool chain you have opted to use, that entirely depends on your personal choices and it's at least upwards-compatible. That's enough to build & run Ingnomia.

No need for any additional components the installer could provide, source code (2.3GB) and debug symbols (6.81 GB) are already optional even though advisable if you intend to debug.
