### ISSUE TITLE
Can't run when Ransomware protection is enabled

### ISSUE THREAD

**Issue by Dambuster88** [rschurade/Ingnomia#99]
The app can't run (for the **first time only**) when the **Ransomware protection** is activated.
Installed from Steam, v0.8.0 on a Windows 10 machine.

How to reproduce:
1. Delete/Rename the **settings** folder from ~\Documents\My Games\Ingnomia
2. Enable Ransomware protection from Windows 10 settings
3. Run the game; it won't run

Workaround:
1. Disable Ransomware protection from Windows 10 settings
2. Run the game for the first time
3. Enable Ransomware protection from Windows 10 settings

In the end, the problem is that the app doesn't have Write permission to ~\Documents\My Games\Ingnomia because of Ransomware protection. Without this permission you will not be able to save settings, save games etc.

**Comment by Dambuster88** [comment]
Actually, the fix is to add the game executable to the **Allow an app through Controlled folder access**, from the **Ransomware protection** settings.

**Comment by Ext3h** [comment]
Not clear how to act on this. The folder `My Documents\My Games` is the folder savegames are supposed to go. Meanwhile `My Documents` is explicitly "protected", so I'm not sure what to do next?

Not to mention that the "Ramsomware Protection" is not even enabled by default.

**Comment by rschurade** [comment]
Not a bug
